// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBApBSyIt0RJGb26EBOrG08Dnn72HAAK5g',
    appId: '1:843907454182:android:116259e3556af2ac62d727',
    messagingSenderId: '843907454182',
    projectId: 'alqadiya-3bb79',
    storageBucket: 'alqadiya-3bb79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbZPpAQ8lfvI9jsfzMZ5mnTozDiUprZvM',
    appId: '1:843907454182:ios:7fa774bede21432c62d727',
    messagingSenderId: '843907454182',
    projectId: 'alqadiya-3bb79',
    storageBucket: 'alqadiya-3bb79.firebasestorage.app',
    androidClientId: '843907454182-aauq7g7dlckplrg36et20mm2604m7k4f.apps.googleusercontent.com',
    iosClientId: '843907454182-khc6d09q45pc6ircfqhdlj5lm921tet7.apps.googleusercontent.com',
    iosBundleId: 'com.vga.alqadiya',
  );
}
